/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/t-shirt.glb -o src/assets/model/TShirt.jsx 
Author: Hyperrealitystudio (https://sketchfab.com/Hyperrealitystudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-7c8a4dede482474fa5a74f24c6fc5e81
Title: T-shirt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/t-shirt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.AM_102_035_003_AM_102_035_002_0.geometry} material={materials.AM_102_035_002} />
    </group>
  )
}

useGLTF.preload('/t-shirt.glb')
